import { Inter, Quicksand } from "next/font/google";
import "./globals.css";
import { Providers } from "./provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

//👇 Configure our font object
const quicksand = Quicksand({
    subsets: ["latin"],
    variable: "--font-quicksand",
});

export default function RootLayout({ children }) {
    return (
        <html lang="en" className={quicksand.className}>
            <body>
                <Providers>{children}</Providers>
            </body>
        </html>
    );
}
